// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idyibazgkwsyqoeskieu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkeWliYXpna3dzeXFvZXNraWV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY2ODQ3MzgsImV4cCI6MjA5MjI2MDczOH0.57AriU_yls7cl_TYRbQq9paqUGMMNlrLNfsFA3ovb_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
